### PR TITLE
Php unit tests in travis

### PR DESCRIPTION
**Pull request by MekDrop**
Added php unit tests

### CODE REVIEW

**Comment by fiammybe** [comment]
Travis works now, thank you for the fix! At least, it doesn't give errors
anymore, I'm not sure if tests are being executed.

Op wo 2 dec. 2015 23:52 schreef Raimondas Rimkevičius <
notifications@github.com>:

**Comment by MekDrop** [comment]
I think tests are executed but process doesn't finish because there are still some fatal errors in the core.

**Comment by fiammybe** [comment]
Ok, those would be on the list to fix for the next release I would expect

Op do 3 dec. 2015 14:09 schreef Raimondas Rimkevičius <
notifications@github.com>:

**Comment by MekDrop** [comment]
I hope to fix all such errors this week ;)

**Comment by fiammybe** [comment]
cool, travis is green now i see
Op 3/12/2015 22:53:54, Raimondas Rimkevičius <notifications@github.com> schreef:
Merged #25 [https://github.com/ImpressCMS/impresscms/pull/25].

**Pull request merged**
