### PR TITLE
Use Aura.SQL for database operations

### PR DESCRIPTION
**Pull request by MekDrop**
Implements #160 .

So, here changes:
* PDO now is requirement not suggestion
* [Aura.SQL](http://auraphp.com/packages/3.x/Sql/) is used now as database connection classes base
* [Aura.SQLSchema](https://github.com/auraphp/Aura.SqlSchema) is also included but not yet used
* Rewritten installer's makedata.php file to be more secure and also to use parameters SQL binding
* Installer now use almost same database connection like installed ICMS
* Because old database also use query method that is used by PDO, old style query method invokation works only if query method is called with 3 arguments, otherwise new method is used. This probably will not affect any IPF modules but some older could have some problems.
* Some code is written that in future could let ICMS use on where scalling is used but right now such functionality is commented - probably we could back there after this pull request will be merged
* $xoopsDB and $db works same
* SQL logging can be not always visible in debug log - I'll plan to look into that later once we add PSR compliant logging mechanism.
* Failed queries usually now will throw exceptions
* Some legacy database classes where removed
* Fixed bug in installer when trying to change encoding and see what collisions are available (probably 1.4 also should be checked for that)

### CODE REVIEW

**Comment by fiammybe** [comment]
I have a problem connecting to the database with an empty password (standard xampp setup, user is 'root' and password is empty)

**Comment by MekDrop** [comment]
@fiammybe I think I have fixes your issue. Also, I found another one - when user can connect to database but database doesn't exists and user doesn't has enough permissions. Please, check when you can.

**Comment by fiammybe** [comment]
in the version checker /htdocs/modules/system/admin.php?fct=version:
Uncaught exception
Message: Class 'icms_db_Connection' does not have a method 'getServerVersion'
Code: 0
File: C:\xampp72\htdocs\impresscms-improvement-aura.sql-for-database\vendor\aura\sql\src\AbstractExtendedPdo.php
Line: 113
Trace:

#0 C:\xampp72\htdocs\impresscms-improvement-aura.sql-for-database\modules\system\admin\version.php(51): Aura\Sql\AbstractExtendedPdo->__call('getServerVersio...', Array)
#1 C:\xampp72\htdocs\impresscms-improvement-aura.sql-for-database\modules\system\admin.php(116): include_once('C:\\xampp72\\htdo...')
#2 C:\xampp72\htdocs\impresscms-improvement-aura.sql-for-database\htdocs\index.php(119): require('C:\\xampp72\\htdo...')
#3 {main}

**Comment by MekDrop** [comment]
@fiammybe, I added small fix for that.

**Pull request merged**
