### PR TITLE
Making input boxes accept wider text strings

### PR DESCRIPTION
**Pull request by jegelstaff**
So email can be used comfortably as a username

### CODE REVIEW

**Comment by fiammybe** [comment]
Thank you for the PR. I'll check if the new length gives problems in the database before accepting it.

**Comment by fiammybe** [comment]
This is for 2.0?

**Comment by jegelstaff** [comment]
No, it's just a fix. If you have a very long username, you can't enter it all in this box.

**Comment by fiammybe** [comment]
The reason I ask is because the master branch is used for ImpressCMS 2.0. If you want it to appear in 1.4, could you please make a PR against the branches/impresscms_1.4 branch? Thanks!

**Pull request merged**
