### PR TITLE
Move wide image from libraries to composer

### PR DESCRIPTION
**Pull request by MekDrop**
Another library moved to composer

### CODE REVIEW

**Comment by fiammybe** [comment]
Cool! I tried to remove WideImage, but I must have missed the preloads part. Now I understand why I couldn’t get it to work. Nice job!

Van: Raimondas Rimkevičius
Verzonden: maandag 29 januari 2018 9:57
Aan: ImpressCMS/impresscms
CC: Subscribed
Onderwerp: [ImpressCMS/impresscms] Move wide image from libraries to composer(#132)

Another library moved to composer

You can view, comment on, or merge this pull request online at:
  https://github.com/ImpressCMS/impresscms/pull/132
Commit Summary
• Removed WideImage manual inclusion
• added wideimage into composer.json
• Removed WideImage from libraries folder
• Removed WideImage from preloads
File Changes
• M htdocs/composer.json (3) 
• M htdocs/libraries/image-editor/image-edit.php (566) 
• M htdocs/libraries/image-editor/plugins/crop/crop_image.php (14) 
• M htdocs/libraries/image-editor/plugins/filter/filter_image.php (14) 
• M htdocs/libraries/image-editor/plugins/resize/resize_image.php (16) 
• M htdocs/libraries/smarty/icms_plugins/function.resized_image.php (19) 
• D htdocs/libraries/wideimage/index.html (1) 
• D htdocs/libraries/wideimage/lib/Canvas.php (167) 
• D htdocs/libraries/wideimage/lib/Coordinate.php (208) 
• D htdocs/libraries/wideimage/lib/Exception.php (31) 
• D htdocs/libraries/wideimage/lib/Font/GDF.php (48) 
• D htdocs/libraries/wideimage/lib/Font/PS.php (60) 
• D htdocs/libraries/wideimage/lib/Font/TTF.php (75) 
• D htdocs/libraries/wideimage/lib/Font/index.html (1) 
• D htdocs/libraries/wideimage/lib/Image.php (964) 
• D htdocs/libraries/wideimage/lib/Mapper/BMP.php (51) 
• D htdocs/libraries/wideimage/lib/Mapper/GD.php (44) 
• D htdocs/libraries/wideimage/lib/Mapper/GD2.php (41) 
• D htdocs/libraries/wideimage/lib/Mapper/GIF.php (50) 
• D htdocs/libraries/wideimage/lib/Mapper/JPEG.php (41) 
• D htdocs/libraries/wideimage/lib/Mapper/PNG.php (41) 
• D htdocs/libraries/wideimage/lib/Mapper/TGA.php (48) 
• D htdocs/libraries/wideimage/lib/Mapper/index.html (1) 
• D htdocs/libraries/wideimage/lib/MapperFactory.php (126) 
• D htdocs/libraries/wideimage/lib/Operation/AddNoise.php (153) 
• D htdocs/libraries/wideimage/lib/Operation/ApplyConvolution.php (48) 
• D htdocs/libraries/wideimage/lib/Operation/ApplyFilter.php (67) 
• D htdocs/libraries/wideimage/lib/Operation/ApplyMask.php (105) 
• D htdocs/libraries/wideimage/lib/Operation/AsGrayscale.php (49) 
• D htdocs/libraries/wideimage/lib/Operation/AsNegative.php (63) 
• D htdocs/libraries/wideimage/lib/Operation/AutoCrop.php (162) 
• D htdocs/libraries/wideimage/lib/Operation/CopyChannelsPalette.php (90) 
• D htdocs/libraries/wideimage/lib/Operation/CopyChannelsTrueColor.php (67) 
• D htdocs/libraries/wideimage/lib/Operation/CorrectGamma.php (48) 
• D htdocs/libraries/wideimage/lib/Operation/Crop.php (86) 
• D htdocs/libraries/wideimage/lib/Operation/Flip.php (54) 
• D htdocs/libraries/wideimage/lib/Operation/GetMask.php (67) 
• D htdocs/libraries/wideimage/lib/Operation/Merge.php (78) 
• D htdocs/libraries/wideimage/lib/Operation/Mirror.php (55) 
• D htdocs/libraries/wideimage/lib/Operation/Resize.php (157) 
• D htdocs/libraries/wideimage/lib/Operation/ResizeCanvas.php (107) 
• D htdocs/libraries/wideimage/lib/Operation/Rotate.php (64) 
• D htdocs/libraries/wideimage/lib/Operation/RoundCorners.php (114) 
• D htdocs/libraries/wideimage/lib/Operation/Unsharp.php (135) 
• D htdocs/libraries/wideimage/lib/Operation/index.html (1) 
• D htdocs/libraries/wideimage/lib/OperationFactory.php (57) 
• D htdocs/libraries/wideimage/lib/PaletteImage.php (136) 
• D htdocs/libraries/wideimage/lib/README (21) 
• D htdocs/libraries/wideimage/lib/TrueColorImage.php (218) 
• D htdocs/libraries/wideimage/lib/VERSION (2) 
• D htdocs/libraries/wideimage/lib/WideImage.php (377) 
• D htdocs/libraries/wideimage/lib/gpl.txt (339) 
• D htdocs/libraries/wideimage/lib/index.html (1) 
• D htdocs/libraries/wideimage/lib/lgpl.txt (504) 
• D htdocs/libraries/wideimage/lib/vendor/JPEXS/bmp.php (537) 
• D htdocs/libraries/wideimage/lib/vendor/JPEXS/ico.php (965) 
• D htdocs/libraries/wideimage/lib/vendor/JPEXS/index.html (1) 
• D htdocs/libraries/wideimage/lib/vendor/de77/BMP.php (264) 
• D htdocs/libraries/wideimage/lib/vendor/de77/TGA.php (206) 
• D htdocs/libraries/wideimage/lib/vendor/de77/index.html (1) 
• D htdocs/libraries/wideimage/lib/vendor/index.html (1) 
• M htdocs/modules/system/admin/images/preview.php (160) 
• D htdocs/plugins/preloads/wideimage.php (39) 
Patch Links:
• https://github.com/ImpressCMS/impresscms/pull/132.patch
• https://github.com/ImpressCMS/impresscms/pull/132.diff

**Comment by MekDrop** [comment]
Still I'm not 100% sure yet if everything is ok. Some parts where I have removed wideimage manual inclusion I didn't tested because I'm not sure from where can I get there. Also, I'm not sure on the impact for modules.

**Comment by fiammybe** [comment]
No problem, that’s what tests are for.


Van: Raimondas Rimkevičius
Verzonden: maandag 29 januari 2018 10:09
Aan: ImpressCMS/impresscms
CC: David Janssens; Review requested
Onderwerp: Re: [ImpressCMS/impresscms] Move wide image from libraries tocomposer (#132)

Still I'm not 100% sure yet if everything is ok. Some parts where I have removed wideimage manual inclusion I didn't tested because I'm not sure from where can I get there. Also, I'm not sure on the impact for modules.

**Comment by skenow** [comment]
With the changes from @fiammybe, I can view the images in a category in admin cpanel. I can duplicate, and change the name and category. I can also delete (all are launched from modules/system/admin/image.php)

Opening the online image editor results in a blank page (libraries/image-editor/image-edit.php)

Opening the image manager while editing a block also results in a fairly blank page (modules/system/admin/images/browser.php)

**Comment by skenow** [comment]
Additional testing -

Preview of the image will not load in system admin: modules/system/admin/images/preview.php Error: "This image failed to load." Related to the change in paths?

The online editor will load, but none of the functions work (crop, filter, resize)

**Comment by fiammybe** [comment]
I was testing the online editor, and can confirm that the operations don't work. It is a bit complicated to debug, due to the use of javascript. Not used to that ;-)
I haven't looked into the paths yet, so it's normal that they  are still broken ;-)

**Comment by MekDrop** [comment]
It seems it was easy fix for image editor. In every PHP file there I needed to add `use WideImage\WideImage;` line and everything started to work.

**Pull request merged**
