### PR TITLE
Replace existing Smarty files with Smarty 3 composer instalation

### LINKED ISSUE #238: Should ICMS use Smarty?
Should we upgrade to [Smaty 3](https://www.smarty.net/docs/en/) or we should use different template engine?

Our options:
* [Dwoo](http://dwoo.org/)- has [smarty compatibility](http://dwoo.org/plugins/processors/smarty-compat.html) layer and is written in object style.
* [Twig](https://twig.symfony.com) - used by Symfony and many others. Similar to smarty but has some differences
* [Blade](https://laravel.com/docs/5.6/blade) - like Twig is similar but it's possible to use PHP code directly in templates

### PR DESCRIPTION
**Pull request by MekDrop**
After #238 I have decided to experiment a bit. So here is Smarty 3 in ICMS! And it seems everything works. 

Smarty 3 doesn't supports text params without quotes, so some templates may need some fixes. F.e.: `<{xoAppUrl /}>` will not work but `<{xoAppUrl '/'}>` should work.

Hardest problem here was `foreachq` and `includeq` both used arguments parsing that doesn't work same way in newer Smarty. So I decided deprecate both methods and reuse instead `foreach` and `include` from smarty distribution in that case. From description it seems that both these functions can be not anymore relevant because now `foreach` and `include` in smarty works differently.

Closes #238

### CODE REVIEW

**Comment by fiammybe** [comment]
I merged this onto the current retro branch, and got this:
Uncaught exception
Message: Too few arguments to function Smarty_Internal_Compile_Include::compile(), 2 passed in C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php on line 629 and exactly 3 expected
Code: 0
File: C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_compile_include.php
Line: 75
Trace: 
```#0 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php(629): Smarty_Internal_Compile_Include->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler))
#1 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php(486): Smarty_Internal_TemplateCompilerBase->compileTag2('includeq', Array, Array)
#2 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templateparser.php(1667): Smarty_Internal_TemplateCompilerBase->compileTag('includeq', Array)
#3 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templateparser.php(2684): Smarty_Internal_Templateparser->yy_r31()
#4 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templateparser.php(2779): Smarty_Internal_Templateparser->yy_reduce(31)
#5 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_smartytemplatecompiler.php(114): Smarty_Internal_Templateparser->doParse(10, '\n\t\t\t}>')
#6 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php(404): Smarty_Internal_SmartyTemplateCompiler->doCompile('compileTemplateSource(Object(Smarty_Internal_Template), false, NULL)
#8 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(204): Smarty_Internal_TemplateCompilerBase->compileTemplate(Object(Smarty_Internal_Template))
#9 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(100): Smarty_Template_Compiled->compileTemplateSource(Object(Smarty_Internal_Template))
#10 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(163): Smarty_Template_Compiled->process(Object(Smarty_Internal_Template))
#11 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#12 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(216): Smarty_Internal_Template->render(false, 1)
#13 C:\xampp71\htdocs\alpha7\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(122): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#14 C:\xampp71\htdocs\alpha7\libraries\icms\view\theme\Object.php(389): Smarty_Internal_TemplateBase->display('C:\\xampp71\\htdo...')
#15 C:\xampp71\htdocs\alpha7\libraries\icms\response\HTML.php(288): icms_view_theme_Object->render()
#16 C:\xampp71\htdocs\alpha7\libraries\icms\response\DefaultEmptyPage.php(26): icms_response_HTML->render()
#17 C:\xampp71\htdocs\alpha7\htdocs\index.php(168): icms_response_DefaultEmptyPage->render()
#18 {main}
```

**Comment by MekDrop** [comment]
Seems basic functionality works. Some templates needs editing because Smarty 3 handles function arguments in a bit different way. For example  `<{cycle values=odd,even assign=class}>` doesn't work so it needs to be changed to `<{cycle values="odd,even" assign="class"}>`.

**Comment by fiammybe** [comment]
It works, except for the admin page (and all that comes after that) . I get the following stack trace : 
''' Fatal error: Uncaught Error: Using $this when not in object context in C:\xampp72\htdocs\impresscms-move-smarty-to-composer\storage\templates_c\default_core^d98ac5ad1b097cefa9a1428eb35b4c6777f11bcf_0.file.user.html.php:34 Stack trace: #0 C:\xampp72\htdocs\impresscms-move-smarty-to-composer\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_5e665f587c09f3_61526662(Object(Smarty_Internal_Template)) #1 C:\xampp72\htdocs\impresscms-move-smarty-to-composer\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) #2 C:\xampp72\htdocs\impresscms-move-smarty-to-composer\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) #3 C:\xampp72\htdocs\impresscms-move-smarty-to-composer\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(385): Smarty_Internal_Template->render() #4 C:\xampp72\htdocs\impress in C:\xampp72\htdocs\impresscms-move-smarty-to-composer\storage\templates_c\default_core^d98ac5ad1b097cefa9a1428eb35b4c6777f11bcf_0.file.user.html.php on line 34
'''

**Comment by MekDrop** [comment]
I previously made smarty 3 work with iTheme, so it seems our others themes had some minor issues. F.e. core theme used php tag in a way that isn't unsupported anymore. Also, there were few minor issues with variables names in templates but I think have made it work. So, when you can give a try.

**Pull request merged**
