### PR TITLE
ticket 912 - added storing of the registration moment to the adduser functionality in the backend.

### PR DESCRIPTION
**Pull request by fiammybe**
ticket 912 - added storing of the registration moment to the adduser functionality in the backend.

### CODE REVIEW

**Comment by MekDrop** [comment]
Just curious: why date('U') but not time() ? I think haven't used date('U') :/

**Comment by fiammybe** [comment]
I was looking for a way to have the epoch, and date('U') gave me that. No other reason.

**Comment by fiammybe** [comment]
Just thinking, would it be better to define a default value in the base user class (icms_Member_user_Object)? that should cover more cases in 1 go

**Comment by MekDrop** [comment]
Yeah that would be a better choice

**Comment by fiammybe** [comment]
I took this in pull request 61

**Pull request closed without merging**
