### PR TITLE
Db fixes for installer php 7.0+

### LINKED ISSUE #79: using mysql_connect in installation - unsupported since php7
Even though I'm using the PDO connection, the installer still tries to connect to mysql with an unsupported function. When I do the setup on PHP 7.0.9 I get the following : 

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp70\htdocs\icms1310\install\page_dbconnection.php:50 Stack trace: #0 {main} thrown in C:\xampp70\htdocs\icms1310\install\page_dbconnection.php on line 50

in file icms1310/install/page_dbconnection.php

### PR DESCRIPTION
**Pull request by MekDrop**
Fixes #79 and also some related bugs. 

Protector module was removed from installer because it uses many lines with old mysql + icms 2.0 runs with new properties system that can replace at least all things about database protection. But otherwise we need to find newer solutions for things that protector was used.

### CODE REVIEW

**Comment by MekDrop** [comment]
It would be awesome for me if you could make this PR one top priority. It could save me some minutes for working with future requests (yeah I'm using PHP 7.x - that's why).

**Comment by fiammybe** [comment]
I’m trying it out now

Verzonden vanuit Mail voor Windows 10

Van: Raimondas Rimkevičius
Verzonden: maandag 29 januari 2018 10:37
Aan: ImpressCMS/impresscms
CC: David Janssens; Review requested
Onderwerp: Re: [ImpressCMS/impresscms] Db fixes for installer php 7.0+ (#128)

It would be awesome for me if you could make this PR one top priority. It could save me some minutes for working with future requests (yeah I'm using PHP 7.x - that's why).

**Comment by fiammybe** [comment]
Some smal issues:

* http://localhost/icms2/install/page_modcheck.php : MySQL Extension is shown as 'Failed', with a green mark
* http://localhost/icms2/install/page_tablescreate.php : Exception : Uncaught exception
Message: Call to a member function read() on boolean
Code: 0
File: C:\xampp72\htdocs\icms2\libraries\icms\core\Filesystem.php
Line: 140
Trace: 
#0 C:\xampp72\htdocs\icms2\install\page_tablescreate.php(32): icms_core_Filesystem::copyRecursive('C:/xampp72/htdo...', 'C:/xampp72/htdo...')
#1 {main}

**Comment by MekDrop** [comment]
I have fixed these two issues + also I added possibility automatically skip modules page if user has only system module. Seems like everything now works.

**Comment by fiammybe** [comment]
Hi, I'm getting further now :-) I get a blank page at http://localhost/icms2php7/install/page_modulesinstall.php

I even tried a 'composer dumpautoload' to make sure the autoloader was correct, but still a blank page.

**Comment by MekDrop** [comment]
Ahrr... I'll look into later today.

**Comment by MekDrop** [comment]
@fiammybe I just recheckouted the branch. I don't get any blank pages. I'm using vagrant box. Maybe it's some kinda startup error? I have no ideas where should I look for possible problem.

**Comment by fiammybe** [comment]
Hi, I downloaded the entire branch from github. I’m using PHP 7.2.1 on XAMPP, perhaps that could be interesting as well. I will try the installation again and see what it gives.

**Comment by MekDrop** [comment]
I use 7.0 from our official vagrant box, so maybe something was introduced later in PHP that could give such behavior? I think I will check about this later when I can.

**Comment by fiammybe** [comment]
That looks to be the case : In PHP 7.1 I can finish the installer until the end, in 7.2 I get the blank page just before the end.

**Pull request merged**
