### PR TITLE
compatibility for non PDO `XOOPS_DB_TYPE`

### PR DESCRIPTION
**Pull request by nao-pon**

### CODE REVIEW

**Comment by fiammybe** [comment]
Hi @nao-pon , many thanks for your proposed changes. Can you explain why this change is needed? I see what you change, but I do not understand why.

Thank you very much.

**Comment by nao-pon** [comment]
Hi @fiammybe :laughing:

I caught a error `class 'SqlUtility' dose not exists` on module install of my develop module X-elFinder. (My ICM `XOOPS_DB_TYPE` is 'mysql')

That code is

```php
include_once XOOPS_ROOT_PATH.'/class/database/sqlutility.php' ;
$sqlutil = new SqlUtility ;
```

full code is https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/oninstall.php

Thanks for your support.

**Comment by nao-pon** [comment]
I changed code.

**Comment by skenow** [comment]
The proposed change appears OK to me - it covers when the calling code has not defined $driver as it should have. Remember - this is a legacy portion of the code and it is dropped in the 2.0 branch.

**Comment by nao-pon** [comment]
@fiammybe , @skenow Thanks! :+1:

**Pull request merged**
