### PR TITLE
Dev/jquery inclusion

### LINKED ISSUE #925: Adjust included jQuery scripts to match new file structure
Console errors trying to include libraries/jquery/ui/ui.min.js. Several other components are also not present.

Scripts and CSS are added to the HTML output in include/cp_functions.php

### PR DESCRIPTION
**Pull request by skenow**
New versions of jQuery and jQuery UI have a different file structures and the includes needed adjusting. Fixes #925

### CODE REVIEW

**Comment by skenow** [comment]
The Todo bot creates a lot of noise...

**Comment by skenow** [comment]
After these changes, the user side block edit dialog appears to be working, too

**Comment by skenow** [comment]
May also resolve #918

**Review by fiammybe — APPROVED** [review]
The block management pop-up works as expected now.

**Pull request merged**
