### PR TITLE
Add IDs to system_userinfo.html file

### PR DESCRIPTION
**Pull request by alvinbunk**
Pull for my own copy.

### CODE REVIEW

**Comment by alvinbunk** [comment]
Need this to help with Test Cases Steve.

**Comment by MekDrop** [comment]
Is not too early to merge this pull request? I see here some id's added however i don't see anything how they are helping to do anything :|

**Comment by alvinbunk** [comment]
MekDrop, IDs have just been added. The Selenium (or whatever tool) will use the IDs on the page to run it's tests.

**Comment by MekDrop** [comment]
Yeah, I understand that however I believe that would be a better if you add in this pull request also at least one test were you are using these new IDs. I think it's a better practice than creating pull requests for very small pieces of the code because some parts of your work can change before you do some final strokes. 

Also, I think if you install [profile module](https://github.com/ImpressCMS/impresscms-module-profile) there is a possibility to add for this page some extra fields. I can't remember now how this works, but I think you should look into and verify that your tests are working when this module is installed too.

**Comment by MekDrop** [comment]
Also, please rename this pull request into something meaningful :)

**Comment by fiammybe** [comment]
@alvinbunk could you rename please?

**Comment by alvinbunk** [comment]
I renamed it!

**Comment by fiammybe** [comment]
Can anyone tell me the status of this? I'm very interested in this idea of automatic tests, but this seems to have been hanging here these last months. I'd like to see it happen :-)

**Comment by MekDrop** [comment]
This pull request doesn't do anything very useful however I don't see any reason why we shouldn't merge it.

**Comment by fiammybe** [comment]
Then we can merge it, as far as I'm concerned. @alvinbunk did the work to prepare it, we should be happy that he wants to, and integrate his work unless it poses a problem (which it doesn't) :-)
Op 12/04/2016 9:32:45, Raimondas Rimkevičius <notifications@github.com> schreef:
This pull request doesn't do anything very useful however I don't see any reason why we shouldn't merge it.

**Comment by alvinbunk** [comment]
FYI, I'm not waiting on this; I've just been busy with a school project that will be taking all of my time. So I won't be looking at the Selenium tests for a long time. It's a good thing though that this file will be merged in. There are a lot of PHP frameworks that have the ability to add/specify id or class values for html elements.

**Pull request merged**
