### PR TITLE
Upgraded middlewares/referrer-spam to 2.0.2 for PHP 8.0 and Composer 2.0 supporr

### PR DESCRIPTION
**Pull request by MekDrop**
[middlewares/referrer-spam](https://github.com/middlewares/referrer-spam/issues/4#issuecomment-738474115) released new version of lib that solves old this lib compatibility problems with new technologies. So here is update!

### CODE REVIEW

**Comment by fiammybe** [comment]
do you think it's a good idea to merge this one already, taking in to account the problems we have with composer 2? Or is this transparent for composer 2 users, and will this give us the ability to test on PHP8?

**Comment by MekDrop** [comment]
composer 2.0 plugins are mostly backward compatible with composer 1.0 so there is no risk

**Review by fiammybe — CHANGES_REQUESTED** [review]
shouldn't there also be a change in the composer.json file?

**Comment by MekDrop** [comment]
I think updated composer.lock is only really needed.

**Comment by MekDrop** [comment]
on another thought adding to composer.json min version constrain would help when we are merging barnches and having some conflicts... so I have fixed that...

**Review by fiammybe — APPROVED** [review]

**Pull request merged**
